### ISSUE TITLE
Problem with disturbance and  non scalar U 

### ISSUE THREAD

**Issue by Ali-Sharahi** [forgi86/pyMPC#1]
lineq_du = np.ones((Nc+1) * nu)*Dumin
        lineq_du[0:nu] += self.uminus1[0:nu] # works for nonscalar u? 
This section of cod didn't work if we didn't have scalar inputs. I tried to set a disturbance as input that we can't control, but I have a problem with this part of your code that.
Could you help me, please?

**Comment by forgi86** [comment]
Hello Ali,

sorry for the late response, I had not seen this message. 

I tried to implement a fix, it is committed now in the dev branch of this repo.

Had to change also a few lines above:

        # - bounds on \Delta u
        Aineq_du = sparse.vstack([sparse.hstack([np.zeros((nu, (Np + 1) * nx)), sparse.eye(nu), np.zeros((nu, (Nc - 1) * nu))]),  # for u0 - u-1
                                  sparse.hstack([np.zeros((Nc * nu, (Np+1) * nx)), -sparse.eye(Nc * nu) + sparse.eye(Nc * nu, k=1)])  # for uk - uk-1, k=1...Np
                                  ]
                                 )
        if self.SOFT_ON:
            Aineq_du = sparse.hstack([Aineq_du, sparse.csc_matrix((Aineq_du.shape[0], n_eps))])

        uineq_du = np.kron(np.ones(Nc+1), Dumax) #np.ones((Nc+1) * nu)*Dumax
        uineq_du[0:nu] += self.uminus1[0:nu]

        lineq_du = np.kron(np.ones(Nc+1), Dumin) #np.ones((Nc+1) * nu)*Dumin
        lineq_du[0:nu] += self.uminus1[0:nu] # works for nonscalar u?

to implement correctly equation 1.13 in my research notes (doc/latex/main.pdf).

Also made a small test in /examples/example_non_scalar.py (also in the dev branch)

Does it work now?

Marco

**Comment by Ali-Sharahi** [comment]
yes but I still didn't get the correct solution, I think I have to check my numbers again.
Thanks a lot
 Ali

**Comment by forgi86** [comment]
OK Ali.
Can you provide me with more details on your problem? How many inputs/outputs/states?

Also note that in pyMPC all inputs are assumed to be manipulated variables, how were you planning to handle the disturbance?

**Comment by Ali-Sharahi** [comment]
I'm trying to do these 2 examples, both of which do well in Matlab, but I want to compare them to Python
I know I have to set Disterbunce as the input. It should not be multiplied by R (weight function) as we cannot have control over disturbances.
[exam_reactionwheelcontrol_corrected_2020-01-17.pdf](https://github.com/forgi86/pyMPC/files/4539682/exam_reactionwheelcontrol_corrected_2020-01-17.pdf)
![Screenshot 2020-04-27 at 15 01 11](https://user-images.githubusercontent.com/62471988/80375146-1790e600-8898-11ea-957b-2b88fc80d82b.png)

**Comment by forgi86** [comment]
Hello Ali, 

in pyMPC all inputs that you specify are manipulated variables, i.e. it will look for an optimal input sequence assuming that you can manipulate that variable. 

Thus, in the temperature control problem, you should only use \dot Q_o as input in pyMPC as you do not control the ambient temperature and the door opening. 

The following tricks may be useful:

* You may also set the input weight Q_u (maybe R for you) to zero and only penalize the input variation with Q_{\delta u}, which is equivalent to having an 'integral effect' in the controller and can eliminate the disturbances at regime.

 * If you know the ambient temperature you can work around the equilibrium and say that your state variable is T - T_amb.

* You may want to use a filter to estimate disturbances and compensate for them. In the example folder of the repo, I have some Kalman Filter (examples/example_inverted_pendulum_kalman.ipynb). There I used the filter to estimate an unmeasured state, but you may also consider the disturbance as special state with no dynamics (i.e. dist_k+1 = dist_k).

**Comment by Ali-Sharahi** [comment]
Thank you for your helpful Antwort I'm still struggling with it icant get a stable controller it's maybe that we use a full matrix of B and manipulate all u inputs it's not that much easy as I thought.
